# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: hello_server_client 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "hello_server_client"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Aleksander Kwiatkowski"]
  s.date = "2014-01-24"
  s.description = "hello_server client lib."
  s.email = "bobikx@poczta.fm"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/hello_server_client.rb"
  ]
  s.homepage = "http://github.com/akwiatkowski/hello_server_client"
  s.licenses = ["LGPLv3"]
  s.rubygems_version = "2.2.1"
  s.summary = "hello_server client lib"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oj>, [">= 0"])
      s.add_runtime_dependency(%q<ohm>, [">= 0"])
      s.add_runtime_dependency(%q<ohm-contrib>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<oj>, [">= 0"])
      s.add_dependency(%q<ohm>, [">= 0"])
      s.add_dependency(%q<ohm-contrib>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<oj>, [">= 0"])
    s.add_dependency(%q<ohm>, [">= 0"])
    s.add_dependency(%q<ohm-contrib>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

